<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option</name>
   <tag></tag>
   <elementGuidId>3c5b8fd6-8333-417c-b4fd-80a0aaab0963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>*//select/option[text()='${value}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>*//select/option[text()='${value}']</value>
      <webElementGuid>bf71180f-7c12-4503-a57f-2c49cdad3b87</webElementGuid>
   </webElementProperties>
</WebElementEntity>
