<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab</name>
   <tag></tag>
   <elementGuidId>dc70e3ae-0154-4776-a7dc-de57dd776e12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[contains(text(),'${label}')][@class]/ancestor::span[@role])</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[contains(text(),'${label}')][@class]/ancestor::span[@role])</value>
   </webElementProperties>
</WebElementEntity>
