import katalon.api.user.User
import katalon.fw.lib.NPages
		
'1. User login to system to get Token'
NPages.nav(User).initRequestObject()
		.setUrl('/users/login')
		.setBasicAuthorizationHeader(token)
		.setJsonContentTypeHeader()
		.setPayLoad(login_body)
		.sendPostRequest()
		.verifyStatusCode(200)
		.getTextOfPropertyResponse(token)

'2. User use token to call API'		
NPages.nav(User).initRequestObject()
   		.setUrl('/user')
   		.setBasicAuthorizationHeader(token)   
   		.setJsonContentTypeHeader()
   		.setPayLoad(add_contact_body)
   		.sendPostRequest()
   		.verifyStatusCode(201)
   		.verifyPropertyValueReponse('firstName', first_name)
   		.verifyPropertyValueReponse('lastName', last_name)
   		.verifyPropertyValueReponse('email', email)

'3. User update the user'
NPages.nav(Contact).initRequestObject()
		.setUrl('/contacts')
		.setBasicAuthorizationHeader(token)
		.setJsonContentTypeHeader()
		.setPayLoad(update_contact_body)
		.sendPostRequest()
		.verifyStatusCode(201)
		.verifyPropertyValueReponse('firstName', first_name_edit)
		.verifyPropertyValueReponse('lastName', last_name_edit)
		.verifyPropertyValueReponse('birthdate', birthday_edit)
		.verifyPropertyValueReponse('email', email_edit)
		.verifyPropertyValueReponse('phone', phone_edit)
		.verifyPropertyValueReponse('street1', street1_edit)
		.verifyPropertyValueReponse('street2', street2_edit)
		.verifyPropertyValueReponse('stateProvince', state_province_edit)
		.verifyPropertyValueReponse('postalCode', postal_code_edit)
		.verifyPropertyValueReponse('country', country_edit)
		.verifyPropertyValueReponse('city', city_edit)
		
'5. User verify contact data after updated'
NPages.nav(Contact).initRequestObject()
		.setUrl('/contacts')
		.setBasicAuthorizationHeader(token)
		.setJsonContentTypeHeader()
		.sendGetRequest()
		.verifyStatusCode(200)
		.verifyPropertyValueExistInResponse('firstName', first_name_edit)
		.verifyPropertyValueExistInResponse('lastName', last_name_edit)
		.verifyPropertyValueExistInResponse('birthdate', birthday_edit)
		.verifyPropertyValueExistInResponse('email', email_edit)
		.verifyPropertyValueExistInResponse('phone', phone_edit)
		.verifyPropertyValueExistInResponse('street1', street1_edit)
		.verifyPropertyValueExistInResponse('street2', street2_edit)
		.verifyPropertyValueExistInResponse('stateProvince', state_province_edit)
		.verifyPropertyValueExistInResponse('postalCode', postal_code_edit)
		.verifyPropertyValueExistInResponse('country', country_edit)
		.verifyPropertyValueExistInResponse('city', city_edit)

													